export { ModalDismissReasons } from "@ngb/modal/ngb-modal-dismiss-reasons"
export { NgbModalConfig, type NgbModalOptions, type NgbModalUpdatableOptions } from "@ngb/modal/ngb-modal-config.service"
export { NgbModal } from "@ngb/modal/ngb-modal.service"
export { NgbModalModule } from "@ngb/modal/ngb-modal.module"
export { NgbActiveModal, NgbModalRef } from "@ngb/modal/ngb-modal-ref"
